# Generated by Django 5.1.7 on 2025-03-22 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='city',
            fields=[
                ('city_id', models.AutoField(primary_key=True, serialize=False)),
                ('city_name', models.CharField(default='', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='country',
            fields=[
                ('country_id', models.AutoField(primary_key=True, serialize=False)),
                ('country_name', models.CharField(default='', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='role',
            fields=[
                ('role_id', models.AutoField(primary_key=True, serialize=False)),
                ('role_title', models.CharField(default='', max_length=255)),
                ('role_description', models.TextField(default='')),
            ],
        ),
        migrations.CreateModel(
            name='state',
            fields=[
                ('state_id', models.AutoField(primary_key=True, serialize=False)),
                ('state_name', models.CharField(default='', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='user',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('user_level_id', models.CharField(default='2', max_length=255)),
                ('user_username', models.CharField(default='', max_length=255, unique=True)),
                ('user_password', models.CharField(default='', max_length=20)),
                ('user_name', models.CharField(default='', max_length=255)),
                ('user_email', models.EmailField(default='', max_length=255)),
                ('user_mobile', models.CharField(default='', max_length=255)),
                ('user_gender', models.CharField(default='', max_length=10)),
                ('user_dob', models.CharField(default='', max_length=255)),
                ('user_city', models.CharField(default='', max_length=255)),
                ('user_state', models.CharField(default='', max_length=255)),
                ('user_country', models.CharField(default='', max_length=255)),
                ('user_add1', models.TextField(default='')),
                ('user_add2', models.TextField(default='')),
                ('user_image', models.CharField(max_length=255, null=True)),
            ],
        ),
    ]
