sonar.projectKey=sales-inventory
sonar.projectName=Sales and Inventory Management System
sonar.projectVersion=1.0

sonar.sources=.
sonar.language=py
sonar.exclusions=**/venv/**, **/migrations/**

sonar.host.url=http://localhost:9000
sonar.login=squ_8e829284fac28aa5fa106bd0134100e1e10d5de1
