# Generated by Django 5.1.7 on 2025-03-22 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='test',
            fields=[
                ('test_id', models.AutoField(primary_key=True, serialize=False)),
                ('test_title', models.CharField(default='2', max_length=255)),
                ('test_cost', models.CharField(default='', max_length=255, unique=True)),
                ('test_duration', models.CharField(default='', max_length=20)),
                ('test_description', models.CharField(default='', max_length=255)),
            ],
        ),
    ]
