# Generated by Django 5.1.7 on 2025-03-22 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='product',
            fields=[
                ('product_id', models.AutoField(primary_key=True, serialize=False)),
                ('product_name', models.CharField(default='', max_length=255)),
                ('product_type_id', models.CharField(default='', max_length=255)),
                ('product_company_id', models.CharField(default='', max_length=255)),
                ('product_price', models.CharField(default='', max_length=255)),
                ('product_image', models.CharField(max_length=255, null=True)),
                ('product_description', models.TextField(default='')),
                ('product_stock', models.CharField(default='', max_length=255)),
            ],
        ),
    ]
